projectworking-copyad/website/auth.py
##have all the routes related to authentication
from flask import Blueprint, render_template, redirect, url_for,flash, request,session
from flask import current_app as app
from itsdangerous import URLSafeTimedSerializer
from flask_mail import Message, Mail
from .import db 
from .import sess
from .models import User,Inventory
from flask_login import login_user,logout_user,login_required,current_user
from werkzeug.security import generate_password_hash, check_password_hash ##used to hash password. Instead of storing passwords in plain text
import re
import redis

from itsdangerous.exc import BadTimeSignature, SignatureExpired
auth = Blueprint("auth",__name__)
serializer = URLSafeTimedSerializer('VdJeu8dSmW-55Zwk')

##regex patterns for input validation
emailpattern='^[a-z 0-9]+[\._]?[a-z 0-9]+[@]\w+[.]\w{2,3}$'
namepattern ='[A-Za-z]{2,25}||\s[A-Za-z]{2,25}'##for first and last name can have a space in between 
zippattern = '^[0-9]{5}$'
phonepattern ='^(\+\d{1,2}\s?)?1?\-?\.?\s?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}$'
schoolidpattern='^[0]{3}[0-9]{6}$'
bdaypattern='^[0-9]{4}[-][0-9]{2}[-][0-9]{2}$'

@auth.route("/login", methods=['GET', 'POST'])##login page
def login():
    ##email pattern
    if request.method == 'POST':
        email = request.form.get("email")
        password = request.form.get("password")

        user = User.query.filter_by(email=email).first()

        if email=='' or password=='':
            flash("Email or password field can't be empty", category="error")
            return redirect(request.url)
        else:
            if re.search(emailpattern, email):##if user typed in the correct email
                if user:##checks if user exists in db
                    if check_password_hash(user.password, password):##hashes the user input password and compares it to the hashed password stored in 'user'
                        login_user(user, remember=True)#remembers wheter session is expired
                        ##--here grabs apps configs
                        app.config.get("SECRET_KEY")
                        app.config.get("SESSION_TYPE")
                        app.config.get("SESSION_PERMANENT")
                        app.config.get("SESSION_USE_SIGNER")
                        app.config.get("SESSION_REDIS")

                        session['SCHOOL_ID'] = user.s_id
                        session['FNAME']=user.fname
                        session['LNAME']=user.lname
                        session['DATE']=user.date_created
                        session['SF']=user.sf
                        session['id']=user.id

                        if user.sf == "Staff":
                            session['ISstaff']="access" ##creates a session if user is staff-->using it in html for add edit and delete
                            app.config.get('mailconfig.cfg')
                                    
                        return redirect(url_for('views.user'))                        
                    else:
                        flash("Incorrect Password!", category="warning")
                        return redirect(request.url)
                else:
                    flash("There is no account with that email address.",category="error")
                    return redirect(request.url)
            else:
                flash("Invalid email", category="error")
                return redirect(request.url)

    return render_template("login.html",user = current_user)

@auth.route("/register", methods=['GET', 'POST'] )##register page-->email validation to registration form link
def register():    
     ##pattern to validate email input   
    app.config.get('mailconfig.cfg')
    mail = Mail(app)

    if request.method == 'POST':
        email = request.form.get("email")
        email_exists = User.query.filter_by(email=email).first()##checks if email is already in use. 
        token = serializer.dumps(email, salt='email-confirm')
        msg = Message('Register Now For The SMU Nursing Inventory',sender = 'buakthaimuay@gmail.com',recipients=[email])       
        link = url_for('auth.confirmed_registration', token=token, _external=True)        
        msg.body = "The link to register is {}".format(link)
        
        if email == '':
            flash("Email field cannot be empty", category="warning")
            return redirect(request.url)
        else:
            if re.search(emailpattern, email):
                if email_exists:
                    flash("Email is already in use.", category="error")
                    return redirect(request.url)
                else:
                    flash("Check your inbox for the registration link using the email address you provided.","success")               
                    mail.send(msg)
                    return redirect(request.url)
            else:
                flash("Invalid Email, please try again.",category="error")
                return redirect(request.url)
    
    return render_template("register.html",user=current_user)

@auth.route('/confirmed_registration/<token>',methods=['GET','POST'])##gets input from confirmed_registration.html
def confirmed_registration(token):
    try:        
        email = serializer.loads(token, salt='email-confirm', max_age=3600)
    except SignatureExpired:
        flash("Token has expired. Please try again.",category="error")
        return redirect(url_for("views.home"))
    except BadTimeSignature:
        flash("Token is invalid. Please try again.",category="error")
        return redirect(url_for("views.home"))
    
    if request.method == "POST":
        fname = request.form.get("fname")
        lname = request.form.get("lname")
        email = request.form.get("email")
        s_id = request.form.get("s_id")
        zip = request.form.get("zip")
        telnum = request.form.get("telnum")##telephone number
        bday = request.form.get("bday")
        sf= request.form.get("sf")##student or staff
        password = request.form.get("password1")
        confirmedpassword = request.form.get("password2")

        
        email_exists = User.query.filter_by(email=email).first()##checks if email email_exists in the db
        schoolid_exists = User.query.filter_by(s_id=s_id).first()##checks if schoolid already exists in the db
        telnum_exists = User.query.filter_by(telnum=telnum).first()##checks if an account with that telephone number exists in the db

        ##regexpatterns        
        if email_exists or schoolid_exists or telnum_exists: ##checks if any of these are true. if so account already exist and cant register an account.
            flash("Account already exists. Pls login with your existing account", category="error")
            return redirect(url_for("views.home"))
        else:
            ##maybe add firstname and lastname length validation
            if email == '' or fname == '' or lname == ''or s_id=='' or zip == '' or telnum =='' or bday =='' or sf == '' or confirmedpassword == '' or password == '':
                flash("All input fields must be filled up",category="warning")
                return redirect(request.url)
            else:
                if re.search(emailpattern, email) and re.search(namepattern, lname) and re.search(namepattern,fname) and re.search(phonepattern,telnum) and re.search(zippattern,zip) and re.search(schoolidpattern, s_id) and re.search(bdaypattern,bday) and sf == 'Staff' or sf =='Student':
                    if password == confirmedpassword and len(password)>=6:
                        new_user = User(email=email, telnum=telnum,s_id=s_id, fname=fname, lname=lname, password=generate_password_hash(password, method='sha256'), sf=sf, zip=zip, bday=bday) ##stores user input using the model created
                        db.session.add(new_user)
                        db.session.commit()
                        login_user(new_user, remember=True)                   
                        flash("Account created successfully", category="success")
                        return redirect(url_for("views.home"))
                    else:
                        flash("passwords don't match up or password needs to be atleast 6 characters long . Pls try again!","error")
                else: 
                    flash("Error in inputs. Please try again!", category="warning")
                    return redirect(request.url)
           
    return render_template('confirmed_registration.html')
    
@auth.route("/forgot_password",methods=['GET', 'POST'])##asks for users email, checks if exists and sends link to change password
def forgot_password():
    
    app.config.get('mailconfig.cfg') ##takes app's current config and takes the mail config from there and import in this function
    mail = Mail(app)

    if request.method == 'POST':
        email = request.form.get("email")
        token = serializer.dumps(email, salt='email-confirm')
        msg = Message('Change your password for the SMU nursing inventory website',sender = 'buakthaimuay@gmail.com',recipients=[email])       
        link = url_for('auth.confirmedforgot_password', token=token, _external=True)        
        msg.body = "The link to change your password is {}".format(link)
        
        user = User.query.filter_by(email=email).first()
        
        if email=='':
            flash("Email field cannot be empty.", category="error")
            return redirect(request.url)
        else:
            if re.search(emailpattern, email):##if user typed in the correct email
                if user:##checks if user exists in db
                    flash("Check your email for the forgot password link",category="success")
                    mail.send(msg)
                    return redirect(request.url)
                else:

projectworking-copyad/website/templates/Check-in.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Check-in</title>
    <!-- insert stylesheets here -->
    <link rel= "stylesheet" type= "text/css" href= "{{ url_for('static',filename='styles3.css') }}">
    <!-- CSS only -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />    
    <link href='https://cdn.datatables.net/1.10.24/css/jquery.dataTables.min.css' rel='stylesheet' type='text/css'>
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
    
</head>
<body>
    {% if session['SCHOOL_ID'] and session['FNAME'] and session ['id'] and user.is_authenticated %}
    <div class="wrapper">
        <nav>     
          <header>
            <span></span>
              {{session['FNAME']}}
            <a></a>
          </header>
          <ul>
            <li><span>Navigation</span></li>
            <li><a style="text-decoration:none" href="{{url_for('views.user')}}">Inventory</a></li>
            <li><a style="text-decoration:none" href="{{url_for('views.user')}}">Add Item</a></li>
            <li><a style="text-decoration:none" href="{{url_for('views.user')}}">Edit Item</a></li>
            <li><a style="text-decoration:none" href="{{url_for('views.user')}}">Delete Item</a></li>
            <li><a class="active" style="text-decoration:none" href="{{url_for('views.Check_in')}}">Check-in</a></li>
            <li><a style="text-decoration:none" href="{{url_for('views.Check_out')}}">Check-out</a></li>
            <li><span>Other</span></li>
            <li><a style="text-decoration:none" href="{{url_for('views.account_info')}}">Account Info</a></li>
            <!--<li><a>Settings</a></li>-->
            <li><a style="text-decoration:none" href="{{url_for('auth.logout')}}">Logout</a></li>
          </ul>        
        </nav>
      
        <main>     
          <h1>P{{session['SCHOOL_ID']}}'s DASHBOARD</h1>
          <div class="container-fluid">
            <div class="row" style="padding:50px;">
                <p><h2>{{session['FNAME']}}'s borrowed items that have not been returned!</h1></p>
                <div >
                    <table id='empTable' class='display dataTable' width='100%'>
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Item product ID</th>
                            <th>Date checked-out</th> <!--date created -->
                            <th>Quantity</th>
                            <th>Check-in!</th>                          
                        </tr>
                        </thead>
                        {% for row in data %}
                          <tr>
                              <th>{{row.id}}</th>
                              <th>{{row.product_id}}</th>
                              <th>{{row.date_borrowed}}</th>
                              <th>{{row.quantity}}</th>
                              <th><a style="text-decoration:none" href="/user/Check-in-confirmed/{{row.id}}">Return</a></th>
                          </tr>
                        {% endfor %}
                        <tbody>
                          
                        </tbody>
                         
                    </table>
                </div>
           </div>
        </div>
        </main>      
      </div>
      {% endif %}
<script>
$(document).ready(function() {
    $('#empTable').DataTable();
} );
</script>

projectworking-copyad/website/templates/Check-out.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8">
    <link rel= "stylesheet" type= "text/css" href= "{{ url_for('static',filename='styles1.css') }}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <title>Check-out</title>
   </head>
<body>
  {% if session['id'] and user.is_authenticated%}
  <div class="container">
    <div class="title">Check-out an item form:</div>
    <div class="content">
      <form method="POST">
        {% with messages = get_flashed_messages(with_categories=true)%}
        {% if messages %}
          {% for category, message in messages%}
            <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
               <span>{{message}}</span>
               <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
          {% endfor %}
         {% endif %}
         {% endwith %}
         <div class="user-details">
          <div class="input-box">
            <span class="details">Product ID</span>
            <input type="text" id="product_id" name ="product_id" placeholder="Enter Product ID" required>
          </div>
        
        </div>
        <div class="button">
          <input type="submit" value="Submit">
        </div>
        <div>
            <a style="text-decoration:none" style="align-items:center" href="{{url_for('views.user')}}">Click here to cancel or go back to dashboard!</a>
        </div>
      </form>
    </div>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
{% endif %}
</html>



projectworking-copyad/website/templates/account_info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Acct Info</title>
    <link rel= "stylesheet" type= "text/css" href= "{{ url_for('static',filename='styles3.css') }}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />    
    <link href='https://cdn.datatables.net/1.10.24/css/jquery.dataTables.min.css' rel='stylesheet' type='text/css'>
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>    
</head>
<body>
    {% if session['SCHOOL_ID'] and session['FNAME'] and session['LNAME'] and session['DATE'] and session['SF'] and user.is_authenticated %}
    <div class="wrapper">
        <nav>     
          <header>
            <span></span>
              {{session['FNAME']}}
            <a></a>
          </header>
          <ul>
            <li><span>Navigation</span></li>
            <li><a style="text-decoration:none" href="{{url_for('views.user')}}">Inventory</a></li>
            <li><a style="text-decoration:none" href="{{url_for('views.add')}}">Add Item</a></li>
            <li><a style="text-decoration:none" href="{{url_for('views.edit')}}">Edit Item</a></li>
            <li><a style="text-decoration:none" href="{{url_for('views.delete')}}">Delete Item</a></li>
            <li><a style="text-decoration:none" href="{{url_for('views.Check_in')}}">Check-in</a></li>
            <li><a style="text-decoration:none" href="{{url_for('views.Check_out')}}">Check-out</a></li>
            <li><span>Other</span></li>
            <li><a class="active" style="text-decoration:none" href="{{url_for('views.account_info')}}">Account Info</a></li>
            <!--<li><a>Settings</a></li>-->
            <li><a style="text-decoration:none" href="{{url_for('auth.logout')}}">Logout</a></li>
          </ul>      
        </nav>     
        <main>     
          <h1>P{{session['SCHOOL_ID']}}'s DASHBOARD</h1>
          <div class="flex-grid">
            <div>
              <h2>Account Information</h2>
              <ul>
                <li>Account owner: {{session['FNAME']}} {{session['LNAME']}}</li>
                <li>Account ID: {{session['SCHOOL_ID']}}</li>
                <li>Account Created: {{session['DATE']}}</li>
                <li>User is a: {{session['SF']}}</li>
              </ul>
            </div>
        </main>      
      </div>
    {% endif %}
<script>
$(document).ready(function() {
    $('#empTable').DataTable();
} );
</script>
</body>
</html>

projectworking-copyad/website/templates/add.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8">
    <link rel= "stylesheet" type= "text/css" href= "{{ url_for('static',filename='styles1.css') }}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <title>Add</title>
   </head>
<body>
  <div class="container">
    <div class="title">Add an item</div>
    <div class="content"> 
      {% if session['ISstaff'] and session['id'] %}     
      <form method="POST">
        {% with messages = get_flashed_messages(with_categories=true)%}
        {% if messages %}
          {% for category, message in messages%}
            <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
               <span>{{message}}</span>
               <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
          {% endfor %}
         {% endif %}
         {% endwith %}
        
         <div class="user-details">
          <div class="input-box">
            <span class="details">Product ID</span>
            <input type="text" id="product_id" name ="product_id" placeholder="Enter Product ID" required>
          </div>
          <div class="input-box">
            <span class="details">Item Name</span>
            <input type="text" id="product_name" name ="product_name" placeholder="Enter Item Name" required>
          </div>
          <div class="input-box">
            <span class="details">Description </span>
            <input type="text"  id="desc" name ="desc" placeholder="Enter Short description" required>
          </div>
          <div class="input-box">
            <span class="details">Item Location</span>
            <input type="text"  id="i_loc" name ="i_loc" placeholder="Enter Item Location" required>
          </div>
          <div class="input-box">
            <span class="details">Quantity</span>
            <input type="number"  id="quantity" name ="quantity" placeholder="Enter Amount" required min="1" max="20000">
          </div>
        </div>
        <div class="button">
          <input type="submit" value="Submit">
        </div>
        <div>
            <a style="text-decoration:none" style="align-items:center" href="{{url_for('views.user')}}">Click here to cancel or go back to dashboard!</a>
        </div>
      {% else %}
        <div>
          <a style="text-decoration:none" style="align-items:center" href="{{url_for('views.user')}}">You don't have access to add to the Inventory!</a>
      </div>
      {% endif %}
      </form>
    </div>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>


projectworking-copyad/website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">   
    <!-- Bootstrap -->
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    
    <title>{% block title %}{% endblock %}</title>
    <link rel= "stylesheet" type= "text/css" href= "{{ url_for('static',filename='styles.css') }}">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet"> 
</head>
<body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <button 
                class="navbar-toggler" 
                type = "button" 
                data-bs-toggle="collapse" 
                data-bs-target="#navbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbar">
                <div class="navbar-nav">
                    <a class="nav-item nav-link" href="{{url_for('views.home')}}">Home</a>
                    <a class="nav-item nav-link" href="{{url_for('auth.login')}}">Login</a>
                    <a class="nav-item nav-link" href="{{url_for('auth.register')}}">Register</a>
                </div>
              </div>
            </div>
        </nav>
       
        {% with messages = get_flashed_messages(with_categories=true)%}
         {% if messages %}
            {% for category, message in messages%}
            <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                <span>{{message}}</span>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endfor %}
         {% endif %}
        {% endwith %}
     
    <section class="gradient">        
            {% block content %}       
            {% endblock %}            
    </section>

    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

</body>
</html>

projectworking-copyad/website/templates/confirmed_registration.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8">
    <link rel= "stylesheet" type= "text/css" href= "{{ url_for('static',filename='styles1.css') }}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <title>Confirmed Registration</title>
   </head>
<body> 
  <div class="container">
    <div class="title">Registration</div>
    <div class="content">
      <form method="POST">
        {% with messages = get_flashed_messages(with_categories=true)%}
        {% if messages %}
          {% for category, message in messages%}
            <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
               <span>{{message}}</span>
               <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
          {% endfor %}
         {% endif %}
         {% endwith %}
        <div class="user-details">
          <div class="input-box">
            <span class="details">First Name</span>
            <input type="text" id="fname" name ="fname" placeholder="Enter your first name" required>
          </div>
          <div class="input-box">
            <span class="details">Last Name</span>
            <input type="text" id="lname" name ="lname" placeholder="Enter your last name" required>
          </div>
          <div class="input-box">
            <span class="details">Email</span>
            <input type="email" id="email" name ="email" placeholder="Enter your email" required>
          </div>
          <div class="input-box">
            <span class="details">School ID Number</span>
            <input type="text" id="s_id" name ="s_id" placeholder="000xxxxxx" required>
          </div>
          <div class="input-box">
            <span class="details">Zip Code</span>
            <input type="text" id="zip" name ="zip" placeholder="Enter your zipcode" required>
          </div>
          <div class="input-box">
            <span class="details">Phone Number</span>
            <input type="tel" id="telnum" name ="telnum" placeholder="1xxxxxxxxxx or xxx xxx xxxx" required>
          </div>
         
          <div class="input-box">
            <span class="details">Birth Date</span>
            <input type="date"  id="bday" name ="bday" required>
          </div>

          <div class="input-box">
            <span class="details">I am a:</span>
            <select id="sf" name="sf" required>
                <option value="Student">Student</option>
                <option value="Staff">Staff</option>
              </select>
          </div>
          
          <div class="input-box">
            <span class="details">Password</span>
            <input type="password"  id="password1" name ="password1" placeholder="password needs to be 6 or more characters" required>
          </div>
          <div class="input-box">
            <span class="details">Confirm Password</span>
            <input type="password"  id="password2" name ="password2" placeholder="Confirm your password" required>
          </div>
        </div>
      
        <div class="button">
          <input type="submit" value="Register">
        </div>
      </form>
    </div>
  </div>
 
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

projectworking-copyad/website/templates/forgot_password.html
{% extends "base.html"%}
{% block title %}Forgot password{% endblock %}
{% block content %}
<form method="POST">    
    <div class="form-group">
        
        <label for="email">Reset Password</label>
        <input type="email" id="email" name="email" class="form-control" placeholder="Enter A Valid Email Address" required/>
       
        <div align="center">
            <button class="btn btn-primary" type = "submit">Submit</button>
        </div>
    </div>
</form>
{% endblock %}

projectworking-copyad/website/templates/home.html
{% extends "base.html"%}
{% block title %}Home{% endblock %}
{% block content %}
<p class = "line">Saint Martin's University Nursing Inventory</p>
{% endblock %}

projectworking-copyad/website/templates/login.html
{% extends "base.html"%}
{% block title %}Login{% endblock %}
{% block content %}
<form method="POST">
    
    <div class="form-group">
        {% if user.is_authenticated %}       
        <div>
            <label><p id="logp">You are currently logged in </label><a href="{{ url_for('views.user') }}">click here to redirect you to user page!</a></p> 
        </div>
        {% else %}
        <h1 id ="login" align="center">Login</h1>
        <label for="email">Email Address:</label>
        <input type="email" id="email" name="email" class="form-control" placeholder="Enter Email Address" required/>
        
        <label for="password">Password:</label>
        <input type="password" id="password" name="password" class="form-control" placeholder="Enter Password" required/>
        <div>
            <label><p id="logp">Forgot your password? </label><a href="{{ url_for('auth.forgot_password') }}">click here!</a></p>          
        </div>
              
        <div align="center">
            <button class="btn btn-primary" type = "submit">Login</button>
        </div>
        {% endif %}
       
    </div>
</form>
{% endblock %}

projectworking-copyad/website/templates/register.html
{% extends "base.html"%}
{% block title %}Register{% endblock %}
{% block content %}
<form method="POST">
    <!--<h1 align="center">Send Registration Link!</h1>-->
    <div class="form-group">
        {% if user.is_authenticated %}
        <div>
            <label><p id="logp">You are currently logged in </label><a href="{{ url_for('views.user') }}">click here to redirect you to user page!</a></p> 
        </div>
        {% else %}
        <label for="email">Email Address:</label>
        <input type="email" id="email" name="email" class="form-control" placeholder="Enter A Valid Email Address"/>
       
        <div align="center">
            <button class="btn btn-primary" type = "submit">Register</button>
        </div>
        {% endif %}
    </div>
</form>
{% endblock %}